version: "2"
services:
  dccn-dicomdf-base:
    build:
      context: ./base
      args:
        - github_username=demo
        - github_password=guessit
    image: dccn-dicomdf-base
  dccn-orthanc:
    build: ./orthanc
    image: dccn-dicomdf-orthanc
    dns:
      - 131.174.44.33
      - 131.174.44.34
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/scripts:/var/lib/orthanc/scripts
      - ./orthanc/plugins:/var/lib/orthanc/plugins
      - /scratch/data_dicom/orthanc/db:/var/lib/orthanc/db
      - /scratch/data_dicom/orthanc/log:/var/lib/orthanc/log
      - /project:/project
  dccn-wlbroker:
    build: ./wlbroker
    image: dccn-dicomdf-wlbroker
    depends_on:
      - dccn-dicomdf-base
    dns:
      - 131.174.44.33
      - 131.174.44.34
    ports:
      - "1234:1234"
    volumes:
      - /scratch/data_dicom/wlbroker:/data/wlbroker
  dccn-cronie-cal2wl:
    build: ./cal2wl
    image: dccn-dicomdf-cal2wl
    depends_on:
      - dccn-dicomdf-base
    dns:
      - 131.174.44.33
      - 131.174.44.34
    volumes:
      - /scratch/data_dicom/wlbroker:/data/wlbroker
      - ./cal2wl/cron:/cron
      - ./cal2wl/config.ini:/opt/config.ini:ro
