version: "2"
services:
  dccn-dicomdf-base:
    build:
      context: ./base
      args:
        - github_username=xxxxxx
        - github_password=xxxxxx
    image: dccn-dicomdf-base
  dccn-orthanc:
    build: ./orthanc
    image: dccn-dicomdf-orthanc
    network_mode: "host"
    volumes:
      - ./orthanc/config:/var/lib/orthanc/etc:ro
      - ./orthanc/scripts:/var/lib/orthanc/scripts
      - ./orthanc/plugins:/var/lib/orthanc/plugins
      - /data/orthanc/db:/var/lib/orthanc/db
      - /scratch/orthanc/idx:/var/lib/orthanc/idx
      - /data/orthanc/log:/var/lib/orthanc/log
      - /project:/project
  dccn-wlbroker:
    build: ./wlbroker
    image: dccn-dicomdf-wlbroker
    depends_on:
      - dccn-dicomdf-base
    network_mode: "host"
    volumes:
      - /data/wlbroker:/data/wlbroker
  dccn-cronie-cal2wl:
    build: ./cal2wl
    image: dccn-dicomdf-cal2wl
    depends_on:
      - dccn-dicomdf-base
    volumes:
      - /data/wlbroker:/data/wlbroker
      - ./cal2wl/cron:/cron
      - ./cal2wl/config:/opt/config:ro
