version: "2"
services:
  dccn-orthanc:
    build: ./orthanc
    ports:
      - "8042:8042"
      - "4042:4042"
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/scripts:/var/lib/orthanc/scripts
      - ./orthanc/plugins:/var/lib/orthanc/plugins
      - /scratch/data_dicom/orthanc/db:/var/lib/orthanc/db
      - /scratch/data_dicom/orthanc/log:/var/lib/orthanc/log
      - /project:/project
  dccn-wlbroker:
    build: ./wlbroker
    ports:
      - "1234:1234"
    volumes:
      - /scratch/data_dicom/wlbroker:/data/wlbroker
