version: "2"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    network_mode: "host"
    volumes:
      - /scratch/data_stager:/data
  dccn-dirdm-irodsclient:
    build:
      context: ./irodsclient
    image: dccn-dirdm-irodsclient
  dccn-dirdm-stager:
    build: ./stager
    image: dccn-dirdm-stager
    network_mode: "host"
    volumes:
      - ./stager/config/default.json:/opt/stager/config/default.json
      - /home:/home:ro
      - /project:/project
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    depends_on:
      - dccn-dirdm-irodsclient
      - redis
